schema_version = 1

[metadata]
"format" = "pipeline29_text"
"schema_version" = 1
"updated_at_utc" = "2026-03-13T20:41:25+00:00"
"source_kind" = "text"
"source_path" = "C:\\Users\\SC61730\\Downloads\\Processamento_mestrado_28\\Processamentos\\config\\pipeline29_text"
